### PR TITLE
WIP: Upgrade  Certificate

### PR DESCRIPTION
**Pull request by oraoto**
See : https://developer.apple.com/support/expiration/

Certificate download from: https://www.apple.com/certificateauthority/AppleWWDRCAG3.cer , converted to PEM format with openssl.

### CODE REVIEW

**Comment by wochaowenya** [comment]
I have finished the certificate update, but the APP keeps flashback, and Zsign is deployed in CentOS

**Comment by oraoto** [comment]
@wochaowenya Did you sign with an old developer certificate?

**Comment by wochaowenya** [comment]
> @wochaowenya您是否使用旧的开发人员证书签名？

Can you tell me how to generate a new certificate?

**Comment by killerpoio** [comment]
Because old  developer certificate are still vaild because the AppleDevCA vaild at 2013.2.8-2023-2.8, so could not just replace AppleDevCA. Should check the issuer name hash, then decide which CA.

**Comment by wochaowenya** [comment]
I can add the old AppleDevCA and AppleDevCA_G3 in the object,it working?

**Comment by oraoto** [comment]
@killerpoio points out the correct way to handle the certificates. 

I close this PR, since it just solve my problem in my particular situation (all certificate are created after 2021.01.28).

**Comment by wochaowenya** [comment]
Thank you ,GodMan!

**Comment by Alaa-Hany** [comment]
@wochaowenya i cant resolve please help me

**Comment by Alaa-Hany** [comment]
@wochaowenya can u help me

**Comment by Alaa-Hany** [comment]
@wochaowenya  can u help me 
after update i have this problem with new certificates 
please help

**Pull request closed without merging**
