### PR TITLE
Fix i os15x i os10x

### PR DESCRIPTION
**Pull request by Xkinda**

### CODE REVIEW

**Comment by xxqy123** [comment]
This pr does not compatible with iOS15.1

**Comment by Xkinda** [comment]
> This pr does not compatible with iOS15.1

I have made a test on iOS15.1, iOS10.3.3, iOS13.5.1, and it all works. Could you please show more error details ?

**Comment by xxqy123** [comment]
> > This pr does not compatible with iOS15.1
> 
> I have made a test on iOS15.1, iOS10.3.3, iOS13.5.1, and it all works. Could you please show more error details ?

iPhone 11 with iOS15.1(19B74), I can resign and install Apps successful, but i can't open it after installed. Just the same as the version in master branch

**Comment by xxqy123** [comment]
> > > This pr does not compatible with iOS15.1
> > 
> > 
> > I have made a test on iOS15.1, iOS10.3.3, iOS13.5.1, and it all works. Could you please show more error details ?
> 
> iPhone 11 with iOS15.1(19B74), I can resign and install Apps successful, but i can't open it after installed. Just the same as the version in master branch

@Xkinda do you have any idea about it? You just add CDHashes, but compared with codesigned apps's CSSLOT_SIGNATURESLOT, it miss CDHashes2 like this:
```
CDHashes2:    1.2.840.113635.100.9.2 => 
            51f7d9c450efb82abc7b05f7972efd7f143e0b97
            21ff0dc3ab74edaba94e232d9345b4d5ae6e7a6b64dc206a1f8c87d0540bdd90 
```

**Comment by Xkinda** [comment]
> > > > This pr does not compatible with iOS15.1
> > > 
> > > 
> > > I have made a test on iOS15.1, iOS10.3.3, iOS13.5.1, and it all works. Could you please show more error details ?
> > 
> > 
> > iPhone 11 with iOS15.1(19B74), I can resign and install Apps successful, but i can't open it after installed. Just the same as the version in master branch
> 
> @Xkinda do you have any idea about it? You just add CDHashes, but compared with codesigned apps's CSSLOT_SIGNATURESLOT, it miss CDHashes2 like this:
> 
> ```
> CDHashes2:    1.2.840.113635.100.9.2 => 
>             51f7d9c450efb82abc7b05f7972efd7f143e0b97
>             21ff0dc3ab74edaba94e232d9345b4d5ae6e7a6b64dc206a1f8c87d0540bdd90 
> ```

I ignored this difference before because it worked for me on my iOS15.1, now maybe I should make more test.

**Pull request merged**
